spring:
  main:
    web-application-type: reactive

  application:
    name: cloud-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**


        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/course/**


      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

server:
  port: 8765

logging:
  level:
    org.springframework.cloud.gateway: DEBUG